/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.FocusEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class Home_GUI extends javax.swing.JFrame {

    private CardLayout cardLayout;
	private JPanel panelKhac;
	private JLabel lbKhac;
	/**
     * Creates new form Home_GUI
     */
    public Home_GUI() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        
        cardPanel.add(new BanVe_GUI(), "banve");
        cardPanel.add(new Phim_GUI(), "phim");
        cardPanel.add(new PhongChieu_GUI(), "phongchieu");
        cardPanel.add(new LichChieu_GUI(), "lichchieu");
        cardPanel.add(new Ghe_GUI(), "ghe");
        cardPanel.add(new SanPham_GUI(), "sanpham");
        cardPanel.add(new GiaoDich_GUI(), "giaodich");
        cardPanel.add(new KhachHang_GUI(), "khachhang");
        cardPanel.add(new NhanVien_GUI(), "nhanvien");
        cardPanel.add(new ThongKe_GUI(), "thongke");
        cardPanel.add(new Ve_GUI(), "ve");
        
    }
    
    private void adjustMenuBasedOnRole(String userRole) {
        if (userRole.equals("NV_QUANLY")) {

        } else if (userRole.equals("NV_LETAN")) {
            panelSanPham.setVisible(false);
            panelThongKe.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelUser3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        panelBanVe = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbBanVe = new javax.swing.JLabel();
        panelPhim = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbPhim = new javax.swing.JLabel();
        panelPhongChieu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbPhongChieu = new javax.swing.JLabel();
        panelLichChieu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lbLichChieu = new javax.swing.JLabel();
        panelThongKe = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        lbThongKe = new javax.swing.JLabel();
        panelSanPham = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        lbSanPham = new javax.swing.JLabel();
        panelGiaoDich = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        lbGiaoDich = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelKhachHang = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        lbKhachHang = new javax.swing.JLabel();
        panelNhanVien = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        lbNhanVien = new javax.swing.JLabel();
        panelGhe = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        lbGhe = new javax.swing.JLabel();
        panelVe = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        lbVe = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        panelDangXuat = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        lbDangXuat = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 300));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        panelUser3.setBackground(new java.awt.Color(255, 255, 255));
        panelUser3.setForeground(new java.awt.Color(255, 102, 0));
        panelUser3.setMaximumSize(new java.awt.Dimension(300, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/user_1.png"))); // NOI18N
        jLabel3.setText("jLabel1");

        lbUserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUserName.setText("Mai Công Thành");

        jSeparator2.setBackground(new java.awt.Color(0, 204, 0));
        jSeparator2.setAlignmentX(10.0F);
        jSeparator2.setAlignmentY(10.0F);
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout panelUser3Layout = new javax.swing.GroupLayout(panelUser3);
        panelUser3.setLayout(panelUser3Layout);
        panelUser3Layout.setHorizontalGroup(
            panelUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUser3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelUser3Layout.setVerticalGroup(
            panelUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUser3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelUser3);

        panelBanVe.setBackground(new java.awt.Color(255, 255, 255));
        panelBanVe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBanVe.setMaximumSize(new java.awt.Dimension(300, 60));
        panelBanVe.setPreferredSize(new java.awt.Dimension(300, 60));
        panelBanVe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelBanVeFocusGained(evt);
            }
        });
        panelBanVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBanVeMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/ticket.png"))); // NOI18N
        jLabel6.setText("jLabel3");

        lbBanVe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbBanVe.setText("Bán vé");
        lbBanVe.setMaximumSize(new java.awt.Dimension(300, 60));
        lbBanVe.setMinimumSize(new java.awt.Dimension(300, 60));
        lbBanVe.setPreferredSize(new java.awt.Dimension(300, 60));

        javax.swing.GroupLayout panelBanVeLayout = new javax.swing.GroupLayout(panelBanVe);
        panelBanVe.setLayout(panelBanVeLayout);
        panelBanVeLayout.setHorizontalGroup(
            panelBanVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBanVeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbBanVe, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panelBanVeLayout.setVerticalGroup(
            panelBanVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBanVeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelBanVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbBanVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelBanVe);

        panelPhim.setBackground(new java.awt.Color(255, 255, 255));
        panelPhim.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 1, 1, 1));
        panelPhim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPhim.setMaximumSize(new java.awt.Dimension(300, 60));
        panelPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPhimMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Phim.png"))); // NOI18N
        jLabel7.setText("jLabel5");

        lbPhim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPhim.setText("Phim");

        javax.swing.GroupLayout panelPhimLayout = new javax.swing.GroupLayout(panelPhim);
        panelPhim.setLayout(panelPhimLayout);
        panelPhimLayout.setHorizontalGroup(
            panelPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPhimLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panelPhimLayout.setVerticalGroup(
            panelPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPhimLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbPhim))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(panelPhim);

        panelPhongChieu.setBackground(new java.awt.Color(255, 255, 255));
        panelPhongChieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPhongChieu.setMaximumSize(new java.awt.Dimension(300, 60));
        panelPhongChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPhongChieuMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/phongChieu.png"))); // NOI18N
        jLabel10.setText("jLabel5");

        lbPhongChieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPhongChieu.setText("Phòng chiếu");

        javax.swing.GroupLayout panelPhongChieuLayout = new javax.swing.GroupLayout(panelPhongChieu);
        panelPhongChieu.setLayout(panelPhongChieuLayout);
        panelPhongChieuLayout.setHorizontalGroup(
            panelPhongChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPhongChieuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbPhongChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        panelPhongChieuLayout.setVerticalGroup(
            panelPhongChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPhongChieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPhongChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbPhongChieu))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(panelPhongChieu);

        panelLichChieu.setBackground(new java.awt.Color(255, 255, 255));
        panelLichChieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelLichChieu.setMaximumSize(new java.awt.Dimension(300, 60));
        panelLichChieu.setPreferredSize(new java.awt.Dimension(300, 60));
        panelLichChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLichChieuMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/LichChieu.png"))); // NOI18N
        jLabel13.setText("jLabel11");

        lbLichChieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbLichChieu.setText("Lịch chiếu");

        javax.swing.GroupLayout panelLichChieuLayout = new javax.swing.GroupLayout(panelLichChieu);
        panelLichChieu.setLayout(panelLichChieuLayout);
        panelLichChieuLayout.setHorizontalGroup(
            panelLichChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLichChieuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbLichChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        panelLichChieuLayout.setVerticalGroup(
            panelLichChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLichChieuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelLichChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbLichChieu))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(panelLichChieu);

        panelThongKe.setBackground(new java.awt.Color(255, 255, 255));
        panelThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelThongKe.setMaximumSize(new java.awt.Dimension(300, 60));
        panelThongKe.setPreferredSize(new java.awt.Dimension(300, 60));
        panelThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelThongKeMouseClicked(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/thongke.png"))); // NOI18N
        jLabel30.setText("jLabel18");

        lbThongKe.setBackground(new java.awt.Color(255, 255, 255));
        lbThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbThongKe.setText("Thống kê");

        javax.swing.GroupLayout panelThongKeLayout = new javax.swing.GroupLayout(panelThongKe);
        panelThongKe.setLayout(panelThongKeLayout);
        panelThongKeLayout.setHorizontalGroup(
            panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongKeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelThongKeLayout.setVerticalGroup(
            panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongKeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(lbThongKe))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(panelThongKe);

        panelSanPham.setBackground(new java.awt.Color(255, 255, 255));
        panelSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelSanPham.setMaximumSize(new java.awt.Dimension(300, 60));
        panelSanPham.setPreferredSize(new java.awt.Dimension(300, 60));
        panelSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSanPhamMouseClicked(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/SanPham.png"))); // NOI18N
        jLabel32.setText("jLabel20");

        lbSanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbSanPham.setText("Sản phẩm/dịch vụ");

        javax.swing.GroupLayout panelSanPhamLayout = new javax.swing.GroupLayout(panelSanPham);
        panelSanPham.setLayout(panelSanPhamLayout);
        panelSanPhamLayout.setHorizontalGroup(
            panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSanPhamLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelSanPhamLayout.setVerticalGroup(
            panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSanPhamLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(lbSanPham))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(panelSanPham);

        panelGiaoDich.setBackground(new java.awt.Color(255, 255, 255));
        panelGiaoDich.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelGiaoDich.setMaximumSize(new java.awt.Dimension(300, 60));
        panelGiaoDich.setPreferredSize(new java.awt.Dimension(300, 60));
        panelGiaoDich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGiaoDichMouseClicked(evt);
            }
        });

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/GiaoDich.png"))); // NOI18N
        jLabel34.setText("jLabel20");

        lbGiaoDich.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGiaoDich.setText("Giao dịch");

        javax.swing.GroupLayout panelGiaoDichLayout = new javax.swing.GroupLayout(panelGiaoDich);
        panelGiaoDich.setLayout(panelGiaoDichLayout);
        panelGiaoDichLayout.setHorizontalGroup(
            panelGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGiaoDichLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(panelGiaoDichLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        panelGiaoDichLayout.setVerticalGroup(
            panelGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGiaoDichLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(lbGiaoDich))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelGiaoDich);

        panelKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        panelKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelKhachHang.setMaximumSize(new java.awt.Dimension(300, 60));
        panelKhachHang.setPreferredSize(new java.awt.Dimension(300, 60));
        panelKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelKhachHangMouseClicked(evt);
            }
        });

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/KhachHang.png"))); // NOI18N
        jLabel39.setText("jLabel20");

        lbKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbKhachHang.setText("Khách hàng");

        javax.swing.GroupLayout panelKhachHangLayout = new javax.swing.GroupLayout(panelKhachHang);
        panelKhachHang.setLayout(panelKhachHangLayout);
        panelKhachHangLayout.setHorizontalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHangLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbKhachHang)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        panelKhachHangLayout.setVerticalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHangLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(lbKhachHang))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(panelKhachHang);

        panelNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        panelNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelNhanVien.setMaximumSize(new java.awt.Dimension(300, 60));
        panelNhanVien.setPreferredSize(new java.awt.Dimension(300, 60));
        panelNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNhanVienMouseClicked(evt);
            }
        });

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Nhanvien.png"))); // NOI18N
        jLabel36.setText("jLabel20");

        lbNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout panelNhanVienLayout = new javax.swing.GroupLayout(panelNhanVien);
        panelNhanVien.setLayout(panelNhanVienLayout);
        panelNhanVienLayout.setHorizontalGroup(
            panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhanVienLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbNhanVien)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        panelNhanVienLayout.setVerticalGroup(
            panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhanVienLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(lbNhanVien))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(panelNhanVien);

        panelGhe.setBackground(new java.awt.Color(255, 255, 255));
        panelGhe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelGhe.setMaximumSize(new java.awt.Dimension(300, 60));
        panelGhe.setPreferredSize(new java.awt.Dimension(300, 60));
        panelGhe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGheMouseClicked(evt);
            }
        });

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Ghe.png"))); // NOI18N
        jLabel37.setText("jLabel20");

        lbGhe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbGhe.setText("Ghế");

        javax.swing.GroupLayout panelGheLayout = new javax.swing.GroupLayout(panelGhe);
        panelGhe.setLayout(panelGheLayout);
        panelGheLayout.setHorizontalGroup(
            panelGheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGheLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbGhe)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        panelGheLayout.setVerticalGroup(
            panelGheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGheLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelGheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(lbGhe))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(panelGhe);

        panelVe.setBackground(new java.awt.Color(255, 255, 255));
        panelVe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelVe.setMaximumSize(new java.awt.Dimension(300, 60));
        panelVe.setPreferredSize(new java.awt.Dimension(300, 60));
        panelVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelVeMouseClicked(evt);
            }
        });

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/ticket.png"))); // NOI18N
        jLabel35.setText("jLabel20");

        lbVe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbVe.setText("Vé");

        javax.swing.GroupLayout panelVeLayout = new javax.swing.GroupLayout(panelVe);
        panelVe.setLayout(panelVeLayout);
        panelVeLayout.setHorizontalGroup(
            panelVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbVe, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(panelVeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
        );
        panelVeLayout.setVerticalGroup(
            panelVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(lbVe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelVe);

        panelDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        panelDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelDangXuat.setMaximumSize(new java.awt.Dimension(300, 60));
        panelDangXuat.setPreferredSize(new java.awt.Dimension(300, 60));
        panelDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDangXuatMouseClicked(evt);
            }
        });

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/exit.png"))); // NOI18N
        jLabel38.setText("jLabel20");

        lbDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbDangXuat.setText("Đăng xuất");

        javax.swing.GroupLayout panelDangXuatLayout = new javax.swing.GroupLayout(panelDangXuat);
        panelDangXuat.setLayout(panelDangXuatLayout);
        panelDangXuatLayout.setHorizontalGroup(
            panelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDangXuatLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panelDangXuatLayout.setVerticalGroup(
            panelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDangXuatLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(lbDangXuat))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(panelDangXuat);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        cardPanel.setBackground(Color.BLACK);
        cardPanel.setPreferredSize(new java.awt.Dimension(1320, 134));
        cardPanel.setLayout(new java.awt.CardLayout());

        jLabel4.setBackground(Color.BLACK);
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 72)); // NOI18N
        jLabel4.setForeground(Color.WHITE);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TSGMCinema");
        cardPanel.add(jLabel4, "card2");

        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

	private void showPanel(String panelName) {
        // Lấy CardLayout từ cardPanel và hiển thị panel tương ứng
        CardLayout cardLayout = (CardLayout) ((JPanel) getContentPane().getComponent(1)).getLayout();
        cardLayout.show((JPanel) getContentPane().getComponent(1), panelName);
    }
    
//    Hàm thay đổi màu khi click chuột
    private void changePanelColor(JPanel selectedPanel, JLabel selectedLabel) {
        // Đặt màu cho panel được chọn
        selectedPanel.setBackground(Color.decode("#199FFE"));
        selectedLabel.setForeground(Color.white);

        // Khôi phục màu cho các panel còn lại
        Color defaultBackgroundColor = Color.white; // Màu nền mặc định của JPanel
        Color defaultTextColor = Color.black; // Màu chữ mặc định
        
        JPanel[] allPanels = { panelBanVe, panelPhim, panelPhongChieu, 
                panelLichChieu, panelThongKe, panelSanPham, panelGiaoDich, 
                panelNhanVien, panelKhachHang,panelGhe, panelVe, panelDangXuat };

		JLabel[] allLabels = { lbBanVe, lbPhim, lbPhongChieu, 
		                lbLichChieu, lbThongKe, lbSanPham, lbGiaoDich, 
		                lbNhanVien, lbKhachHang, lbGhe, lbVe, lbDangXuat };

        for (int i = 0; i < allPanels.length; i++) {
        	if (allPanels[i] != null && allPanels[i] != selectedPanel ) {  // Kiểm tra nếu panel không null
        		allPanels[i].setBackground(defaultBackgroundColor);
            }
            if (allLabels[i] != null && allLabels[i] != selectedLabel) {  // Kiểm tra nếu label không null
            	allLabels[i].setForeground(defaultTextColor);
            }
        }
    }          
    
    private void panelBanVeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelBanVeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_panelBanVeFocusGained

    private void panelVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVeMouseClicked
        // TODO add your handling code here:
    	changePanelColor(panelVe, lbVe);
        
        showPanel("ve");
    }//GEN-LAST:event_panelVeMouseClicked
    
    
    private void panelBanVeMouseClicked(java.awt.event.MouseEvent evt) {
    	changePanelColor(panelBanVe, lbBanVe);
        
        showPanel("banve");
    }  

    private void panelPhimMouseClicked(java.awt.event.MouseEvent evt) {
    	changePanelColor(panelPhim, lbPhim);
        
        showPanel("phim");
    }                                          

    private void panelPhongChieuMouseClicked(java.awt.event.MouseEvent evt) {
    	changePanelColor(panelPhongChieu, lbPhongChieu);
    	
    	showPanel("phongchieu");
    }                                               

    private void panelLichChieuMouseClicked(java.awt.event.MouseEvent evt) {
    	changePanelColor(panelLichChieu, lbLichChieu);
        showPanel("lichchieu");
    }   
    
    private void panelGheMouseClicked(java.awt.event.MouseEvent evt) {
    	changePanelColor(panelGhe, lbGhe);
        showPanel("ghe");
    }   
    
    private void panelSanPhamMouseClicked(java.awt.event.MouseEvent evt) {
    	changePanelColor(panelSanPham, lbSanPham);
        showPanel("sanpham");
    }  
    
    private void panelGiaoDichMouseClicked(java.awt.event.MouseEvent evt) {
    	changePanelColor(panelGiaoDich, lbGiaoDich);
        showPanel("giaodich");
    }  
    
    private void panelKhachHangMouseClicked(java.awt.event.MouseEvent evt) {
    	changePanelColor(panelKhachHang, lbKhachHang);
        showPanel("khachhang");
    }  
    
    private void panelNhanVienMouseClicked(java.awt.event.MouseEvent evt) {
    	changePanelColor(panelNhanVien, lbNhanVien);
        showPanel("nhanvien");
    }  
    private void panelThongKeMouseClicked(java.awt.event.MouseEvent evt) {
    	changePanelColor(panelThongKe, lbThongKe);
        showPanel("thongke");
    }                                 


    private void panelDangXuatMouseClicked(java.awt.event.MouseEvent evt) {
    	changePanelColor(panelDangXuat, lbDangXuat);
        int response = JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất không?", "Xác nhận", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        // Nếu người dùng chọn "Có" (JOptionPane.YES_OPTION)
        if (response == JOptionPane.YES_OPTION) {
            // Quay về trang đăng nhập
            Login_GUI login = new Login_GUI();
            login.setVisible(true);
            this.dispose();  // Đóng trang Home
        } 
        // Nếu chọn "Không" thì không làm gì, chỉ đóng hộp thoại
        
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Home_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbBanVe;
    private javax.swing.JLabel lbDangXuat;
    private javax.swing.JLabel lbGhe;
    private javax.swing.JLabel lbGiaoDich;
    private javax.swing.JLabel lbKhachHang;
    private javax.swing.JLabel lbLichChieu;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JLabel lbPhim;
    private javax.swing.JLabel lbPhongChieu;
    private javax.swing.JLabel lbSanPham;
    private javax.swing.JLabel lbThongKe;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JLabel lbVe;
    private javax.swing.JPanel panelBanVe;
    private javax.swing.JPanel panelDangXuat;
    private javax.swing.JPanel panelGhe;
    private javax.swing.JPanel panelGiaoDich;
    private javax.swing.JPanel panelKhachHang;
    private javax.swing.JPanel panelLichChieu;
    private javax.swing.JPanel panelNhanVien;
    private javax.swing.JPanel panelPhim;
    private javax.swing.JPanel panelPhongChieu;
    private javax.swing.JPanel panelSanPham;
    private javax.swing.JPanel panelThongKe;
    private javax.swing.JPanel panelUser3;
    private javax.swing.JPanel panelVe;
    // End of variables declaration//GEN-END:variables
}
